server: "hub.browserstack.com"
user: "sumitragodara_4scbil"
key: "ytmE793uvurqcqLh1aeV"

common_caps:
  "build": "browserstack-build-1"
  "name": "BStack local test"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
    "browserstack.local": true