server: "hub.browserstack.com"
user: "sumitragodara_4scbil"
key: "ytmE793uvurqcqLh1aeV"

common_caps:
  "build": "browserstack-build-1"
  "name": "BStack parallel test"
  "browserstack.debug": true

browser_caps:
   -
     "browser": "chrome"
     "browser_version": "latest"
     "os": "Windows"
     "os_version": "10"
   -
     "browser": "firefox"
     "browser_version": "latest-beta"
     "os": "Windows"
     "os_version": "10"
   -
     "browser": "firefox"
     "browser_version": "120"
     "os": "Windows"
     "os_version": "11"
   -
     "browser": "chrome"
     "browser_version": "120"
     "os": "OS X"
     "os_version": "Big Sur"
   -
     "browser": "Safari"
     "browser_version": "16.5"
     "os": "OS X"
     "os_version": "Ventura"